spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: ${REACTIVE_DB_HOST:r2dbc:postgresql://localhost:5432/student_manager}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

springdoc:
  api-docs:
    enabled: false