#!/bin/bash

if ! command -v minikube &>/dev/null; then
  echo "Minikube not found - installing..."
  curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  sudo install minikube-linux-amd64 /usr/local/bin/minikube
fi

minikube start

minikube kubectl -- apply -f ./pearl-bailey-high-school/namespaces

minikube kubectl -- apply -f ./pearl-bailey-high-school/secrets

minikube kubectl -- apply -f ./pearl-bailey-high-school/configmaps

minikube kubectl -- apply --recursive -f ./pearl-bailey-high-school/services

minikube kubectl -- apply -f ./pearl-bailey-high-school/networkpolicies

minikube kubectl -- apply -f ./pearl-bailey-high-school/deployments/db

sleep 30s

minikube kubectl -- apply -f ./pearl-bailey-high-school/deployments/app-server
