ARG JDK_VERSION=17

FROM gradle:7.5.1-jdk${JDK_VERSION}-alpine AS build-env

WORKDIR /pearl-bailey-high-school

COPY ./.gradle ./.gradle
COPY ./gradle ./gradle
COPY ./server ./server
COPY ./build.gradle.kts ./build.gradle.kts
COPY ./settings.gradle.kts ./settings.gradle.kts

RUN gradle --no-daemon clean server:build

FROM gcr.io/distroless/java${JDK_VERSION}-debian11:nonroot

USER nonroot:nonroot

COPY --from=build-env /pearl-bailey-high-school/server/build/libs/server-0.0.1-SNAPSHOT.jar /pearl-bailey-high-school-server.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/pearl-bailey-high-school-server.jar"]
