apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-server-db-policy
spec:
  podSelector:
    matchLabels:
      type: app-server-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              type: app-server
