apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: department-manager-db
spec:
  podSelector:
    matchLabels:
      type: app-server-db
      app-name: department-manager
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              type: app-server
              app-name: department-manager
