apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrolment-manager-db
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app-server-db
      app-name: enrolment-manager
  template:
    metadata:
      name: enrolment-manager-db
      namespace: db
      labels:
        type: app-server-db
        app-name: enrolment-manager
    spec:
      hostname: enrolment-manager
      restartPolicy: Always
      containers:
        - name: enrolment-manager-db-server
          image: postgres:14-alpine
          envFrom:
            - configMapRef:
                name: enrolment-manager-db
            - secretRef:
                name: enrolment-manager-db
          ports:
            - containerPort: 5432
              hostPort: 5432
