name: Build Pearl Bailey High School

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      student-manager: ${{ steps.filter.outputs.student-manager }}
      teacher-manager: ${{ steps.filter.outputs.teacher-manager }}
      course-manager: ${{ steps.filter.outputs.course-manager }}
      department-manager: ${{ steps.filter.outputs.department-manager }}
      course-milestone-manager: ${{ steps.filter.outputs.course-milestone-manager }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            student-manager:
              - 'student-manager/**'
              - 'student-manager-api/**'
            teacher-manager:
              - 'teacher-manager/**'
              - 'teacher-manager-api/**'
            course-manager:
              - 'course-manager/**'
              - 'course-manager-api/**'
            department-manager:
              - 'department-manager/**'
              - 'department-manager-api/**'
            course-milestone-manager:
              - 'course-milestone-manager/**'
              - 'course-milestone-manager-api/**'

  build-student-manager:
    needs: changes
    if: ${{ needs.changes.outputs.student-manager == 'true' }}
    uses: dylanhamersztein/pearl-bailey-high-school/.github/workflows/build-microservice-in-docker.yml@master
    secrets: inherit
    with:
      project-to-build: 'student-manager'

  build-teacher-manager:
    needs: changes
    if: ${{ needs.changes.outputs.teacher-manager == 'true' }}
    uses: dylanhamersztein/pearl-bailey-high-school/.github/workflows/build-microservice-in-docker.yml@master
    secrets: inherit
    with:
      project-to-build: 'teacher-manager'

  build-course-manager:
    needs: changes
    if: ${{ needs.changes.outputs.course-manager == 'true' }}
    uses: dylanhamersztein/pearl-bailey-high-school/.github/workflows/build-microservice-in-docker.yml@master
    secrets: inherit
    with:
      project-to-build: 'course-manager'

  build-department-manager:
    needs: changes
    if: ${{ needs.changes.outputs.department-manager == 'true' }}
    uses: dylanhamersztein/pearl-bailey-high-school/.github/workflows/build-microservice-in-docker.yml@master
    secrets: inherit
    with:
      project-to-build: 'department-manager'

  build-course-milestone-manager:
    needs: changes
    if: ${{ needs.changes.outputs.course-milestone-manager == 'true' }}
    uses: dylanhamersztein/pearl-bailey-high-school/.github/workflows/build-microservice-in-docker.yml@master
    secrets: inherit
    with:
      project-to-build: 'course-milestone-manager'
