name: Build Pearl Bailey High School app server in Docker and publish.

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -f ./docker/Dockerfile-server-app -t dylanhamersztein/pearl-bailey-high-school:app-server .
    - name: Docker login
      if: github.event_name != 'pull_request'
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER $DOCKER_PASSWORD
    - name: Docker push
      if: github.event_name != 'pull_request'
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: docker push $DOCKER_USER/pearl-bailey-high-school
