name: Build an image in Docker

on:
  workflow_call:
    inputs:
      project-to-build:
        required: true
        type: string
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-microservice-in-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build --build-arg project_name=${{ inputs.project-to-build }} -t $DOCKER_USER/pearl-bailey-high-school:${{ inputs.project-to-build }} -f ./docker/Dockerfile-microservice .
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        if: github.event_name != 'pull_request'
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker push
        run: docker push $DOCKER_USER/pearl-bailey-high-school:${{ inputs.project-to-build }}
        if: github.event_name != 'pull_request'
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
