name: Build an image in Docker

on:
  workflow_call:
    inputs:
      project-to-build:
        required: true
        type: string

jobs:
  build-microservice-in-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Run Gradle Build for ${{ inputs.project-to-build }}
        run: ./gradlew :${{ inputs.project-to-build }}:clean :${{ inputs.project-to-build }}:test :${{ inputs.project-to-build }}:bootJar --no-daemon
