name: Build and Publish Pearl Bailey High School

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      student-manager: ${{ steps.filter.outputs.student-manager }}
      teacher-manager: ${{ steps.filter.outputs.teacher-manager }}
      course-manager: ${{ steps.filter.outputs.course-manager }}
      department-manager: ${{ steps.filter.outputs.department-manager }}
      course-milestone-manager: ${{ steps.filter.outputs.course-milestone-manager }}
      enrolment-manager: ${{ steps.filter.outputs.enrolment-manager }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Check which files have been changed
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            student-manager:
              - 'student-manager/**'
              - 'student-manager-api/**'
            teacher-manager:
              - 'teacher-manager/**'
              - 'teacher-manager-api/**'
            course-manager:
              - 'course-manager/**'
              - 'course-manager-api/**'
            department-manager:
              - 'department-manager/**'
              - 'department-manager-api/**'
            course-milestone-manager:
              - 'course-milestone-manager/**'
              - 'course-milestone-manager-api/**'
            enrolment-manager:
              - 'enrolment-manager/**'
              - 'enrolment-manager-api/**'

  build-student-manager:
    name: 'Build Student Manager'
    needs: changes
    if: ${{ needs.changes.outputs.student-manager == 'true' }}
    uses: ./.github/workflows/build-microservice-in-docker.yml
    secrets: inherit
    with:
      project-to-build: 'student-manager'

  build-teacher-manager:
    name: 'Build Teacher Manager'
    needs: changes
    if: ${{ needs.changes.outputs.teacher-manager == 'true' }}
    uses: ./.github/workflows/build-microservice-in-docker.yml
    secrets: inherit
    with:
      project-to-build: 'teacher-manager'

  build-course-manager:
    name: 'Build Course Manager'
    needs: changes
    if: ${{ needs.changes.outputs.course-manager == 'true' }}
    uses: ./.github/workflows/build-microservice-in-docker.yml
    secrets: inherit
    with:
      project-to-build: 'course-manager'

  build-department-manager:
    name: 'Build Department Manager'
    needs: changes
    if: ${{ needs.changes.outputs.department-manager == 'true' }}
    uses: ./.github/workflows/build-microservice-in-docker.yml
    secrets: inherit
    with:
      project-to-build: 'department-manager'

  build-course-milestone-manager:
    name: 'Build Course Milestone Manager'
    needs: changes
    if: ${{ needs.changes.outputs.course-milestone-manager == 'true' }}
    uses: ./.github/workflows/build-microservice-in-docker.yml
    secrets: inherit
    with:
      project-to-build: 'course-milestone-manager'

  build-enrolment-manager:
    name: 'Build Enrolment Manager'
    needs: changes
    if: ${{ needs.changes.outputs.enrolment-manager == 'true' }}
    uses: ./.github/workflows/build-microservice-in-docker.yml
    secrets: inherit
    with:
      project-to-build: 'enrolment-manager'
